name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (use Node.js 20 LTS)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Fix Binary Permissions
      - name: Fix Binary Permissions
        run: chmod +x node_modules/.bin/*

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright Tests and Generate JSON Report
      - name: Run Playwright Tests with JSON Report
        run: |
          npx playwright test --reporter=json > test-results.json
        continue-on-error: true # Continue even if tests fail

      # Process Test Results and Generate Summary
      - name: Generate Test Summary
        run: |
          if [[ -f test-results.json ]]; then
            echo "Processing test results..."
            PASSED=$(jq '[.suites[].specs[] | select(.tests[].results[].status == "passed")] | length' test-results.json 2>/dev/null || echo "0")
            FAILED=$(jq '[.suites[].specs[] | select(.tests[].results[].status == "failed")] | length' test-results.json 2>/dev/null || echo "0")
            SKIPPED=$(jq '[.suites[].specs[] | select(.tests[].results[].status == "skipped")] | length' test-results.json 2>/dev/null || echo "0")
            echo "### 🎉 Test Results Summary 🎉" >> $GITHUB_STEP_SUMMARY
            echo "| Status  | Count |" >> $GITHUB_STEP_SUMMARY
            echo "|---------|-------|" >> $GITHUB_STEP_SUMMARY
            echo "| ✅ Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
            echo "| ❌ Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
            echo "| ⏭ Skipped | $SKIPPED |" >> $GITHUB_STEP_SUMMARY
          else
            echo "No test-results.json file found. Please check the test command."
            exit 1
          fi

      # Ensure the Workflow Fails if Any Tests Failed
      - name: Fail Workflow if Tests Failed
        if: failure() # Proceed only if the previous steps failed
        run: exit 1
